//Set Location
export const  SET_LOCATION_REQUEST = 'SET_LOCATION_REQUEST'
export const  SET_LOCATION_SUCCESS = 'SET_LOCATION_SUCCESS'
export const  SET_LOCATION_FAIL = 'SET_LOCATION_FAIL'
export const  SET_LOCATION_RESET = 'SET_LOCATION_RESET'

//Get Location
export const  GET_LOCATION_REQUEST = 'GET_LOCATION_REQUEST'
export const  GET_LOCATION_SUCCESS = 'GET_LOCATION_SUCCESS'
export const  GET_LOCATION_FAIL = 'GET_LOCATION_FAIL'
export const  GET_LOCATION_RESET = 'GET_LOCATION_RESET'
