//SEARCH
export const  SEARCH_REQUEST = 'SEARCH_REQUEST'
export const  SEARCH_SUCCESS = 'SEARCH_SUCCESS'
export const  SEARCH_FAIL = 'SEARCH_FAIL'
export const  SEARCH_RESET = 'SEARCH_RESET'

//Search Product Shop Details
export const  SEARCH_PRODUCT_SHOP_DETAILS_REQUEST = 'SEARCH_PRODUCT_SHOP_DETAILS_REQUEST'
export const  SEARCH_PRODUCT_SHOP_DETAILS_SUCCESS = 'SEARCH_PRODUCT_SHOP_DETAILS_SUCCESS'
export const  SEARCH_PRODUCT_SHOP_DETAILS_FAIL = 'SEARCH_PRODUCT_SHOP_DETAILS_FAIL'
export const  SEARCH_PRODUCT_SHOP_DETAILS_RESET = 'SEARCH_PRODUCT_SHOP_DETAILS_RESET'


